ECHO OFF
PATH A:\;A:\SYS;A:\BIN;A:\BASIC2;A:\ETC;A:\CC;A:\BC
set lib=A:\LIB
set cc=A:\CC
set include=A:\INCLUDE
SET FASTIO=DONE
IF %FASTIO% == DONE GOTO SKIP
FASTIO 384 -S32 -D -F -E
FASTSEEK 128
FASTOPEN 100
SET FASTIO=DONE
:SKIP
