ECHO OFF
PATH A:\;H:\xcoy\SYS;H:\xcoy\BIN;A:\BASIC2;H:\xcoy\ETC;H:\xcoy\CC;H:\xcoy\BC
set lib=H:\xcoy\LIB
set cc=H:\xcoy\CC
set include=H:\xcoy\INCLUDE
SET FASTIO=DONE
IF %FASTIO% == DONE GOTO SKIP
FASTIO 384 -S32 -D -F -E
FASTSEEK 128
FASTOPEN 100
SET FASTIO=DONE
:SKIP

